accessing
exception: anException
	^ self new
		exception: anException;
		yourself